############################
# Teste de submição de job #
############################
#
# Esse teste não funciona sempre. Tentei várias coisas, mas parece que 
# quando eu salvo o arquivo em outro diretório que não o atual, ele 
# pode dar erro na hora de salvar o arquivo (as vezes da e as vezes nao)
#

Path 			= result/test/
k			= 1
BASsize			= 3
iterations 		= 100

Executable		= complete.exe
Universe 		= vanilla
should_transfer_files	= IF_NEEDED
when_to_transfer_output	= ON_EXIT
# requirements         	= TARGET.Machine == node11 
Arguments		= "$(Step) $(Path) $(Step) $(BASsize) $(k) $(iterations)"
Log 			= log/test_$(Step).log
Output			= out/test_$(Step).out
Error 			= error/test_$(Step).err
transfer_input_files    = $(Path)
transfer_output_files   = $(Path)nll_progress_complete_k$(k)-run$(Step).csv

Queue 2

